# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8chvochrvJX8j2OyjTrjjfeOnqftFWP
"""

class KutuphaneYonetimSistemi:
    def _init_(self):
        self.kitaplar = {}
        self.kullanicilar = {}
        self.odunc_kitaplar = {}

    def kitap_ekle(self, kitap_id, kitap_adi, miktar):
       if kitap_id in self.kitaplar:
            self.kitaplar[kitap_id]['miktar'] += miktar
       else:
            self.kitaplar[kitap_id] = {'ad': kitap_adi, 'miktar': miktar}
       print("Kitap başarıyla eklendi.")

    def kitaplari_listele(self):
        for kitap_id, kitap_bilgileri in self.kitaplar.items():
            print(f"Kimlik: {kitap_id}, Ad: {kitap_bilgileri['ad']}, Miktar: {kitap_bilgileri['miktar']}")

    def kullanici_ekle(self, kullanici_id, kullanici_adi):
        if kullanici_id not in self.kullanicilar:
            self.kullanicilar[kullanici_id] = {'ad': kullanici_adi, 'odunc_kitaplar': []}
            print("Kullanıcı başarıyla eklendi!")
        else:
            print("Kullanıcı zaten mevcut.")

    def kitap_odunc_al(self, kullanici_id, kitap_id):
        if kullanici_id not in self.kullanicilar:
            print("Kullanıcı bulunamadı.")
            return
        if kitap_id not in self.kitaplar or self.kitaplar[kitap_id]['miktar'] == 0:
            print("Kitap mevcut değil.")
            return
        self.kitaplar[kitap_id]['miktar'] -= 1
        self.kullanicilar[kullanici_id]['odunc_kitaplar'].append(kitap_id)
        print("Kitap başarıyla ödünç alındı.")

    def kitap_iade_et(self, kullanici_id, kitap_id):
        if kullanici_id not in self.kullanicilar or kitap_id not in self.kullanicilar[kullanici_id]['odunc_kitaplar']:
            print("Geçersiz iade işlemi.")
            return
        self.kitaplar[kitap_id]['miktar'] += 1
        self.kullanicilar[kullanici_id]['odunc_kitaplar'].remove(kitap_id)
        print("Kitap başarıyla iade edildi.")

    def kullanicinin_odunc_aldigi_kitaplari_listele(self, kullanici_id):
        if kullanici_id not in self.kullanicilar:
            print("Kullanıcı bulunamadı.")
            return
        kitaplar = self.kullanicilar[kullanici_id]['odunc_kitaplar']
        if not kitaplar:
            print("Kullanıcı henüz kitap ödünç almamış.")
        else:
            for kitap_id in kitaplar:
                print(f"Kimlik: {kitap_id}, Ad: {self.kitaplar[kitap_id]['ad']}")

sistem = KutuphaneYonetimSistemi()
sistem.kitap_ekle(1, "1984", 5)
sistem.kitap_ekle(2, "Savaş ve Barış", 3)
sistem.kitaplari_listele()
sistem.kullanici_ekle(101, "Ahmet")
sistem.kullanici_ekle(102, "Ayşe")
sistem.kitap_odunc_al(101, 1)
sistem.kitap_odunc_al(102, 2)
sistem.kullanicinin_odunc_aldigi_kitaplari_listele(101)
sistem.kitap_iade_et(101, 1)
sistem.kullanicinin_odunc_aldigi_kitaplari_listele(101)